### PR TITLE
Official Gradle Wrapper Validation GitHub Action

### PR DESCRIPTION
**Pull request by JLLeitschuh**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring

## :scroll: Description

Add a GitHub Action for verifying that the `gradle-wrapper.jar` is an official Gradle release.

## :bulb: Motivation and Context

See: https://github.com/gradle/wrapper-validation-action

## :pencil: Checklist

- [ ] I ran `./gradlew spotlessApply` before submitting the PR
- [ ] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] All tests passing

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Friendly ping?

**Comment by nickbutcher** [comment]
Thanks for the contribution!

**Comment by anticafe** [comment]
Oh, first time I know about [wrapper-validation-action](https://github.com/gradle/wrapper-validation-action) - it would be helpful to protect us from malicious gradle-wrapper.jar. How do you know about it @JLLeitschuh ?

**Comment by JLLeitschuh** [comment]
@anticafe I'm one of the authors (mostly did documentation for it though) and I also work for Gradle.

I wrote our blog post about it:
https://blog.gradle.org/gradle-wrapper-checksum-verification-github-action

**Pull request merged**
